---

# Install python-pip
- name: Install python-pip | Debian
  apt: name=python-pip state=present
  when: ansible_os_family|lower == 'debian'

- name: Install python-pip | RedHat
  yum: name=python-pip state=present
  when: ansible_os_family|lower == 'redhat'

# Install elasticsearch-curator python package
- name: Install elasticsearch-curator
  pip: 
    name: elasticsearch-curator
    version: "{{ elasticsearch_curator_version }}"
    state: present

# Configuration files
- name: Create elasticsearch-curator config dir
  file:
    path:  "{{ elasticsearch_curator_conf_dir }}"
    state: directory

- name: Create elasticsearch-curator config file
  template:
    src:   curator.yml.j2
    dest:  "{{ elasticsearch_curator_conf_dir }}/curator.yml"
    owner: root
    group: root
    mode:  0644

- name: Create elasticsearch-curator actions config file
  template:
    src:   actions.yml.j2
    dest:  "{{ elasticsearch_curator_conf_dir }}/{{ elasticsearch_curator_action_set_item.key }}.yml"
    owner: root
    group: root
    mode:  0644
  with_dict: "{{ elasticsearch_curator_action_sets }}"
  loop_control:
    loop_var: elasticsearch_curator_action_set_item

- name: Create cron jobs for elasticsearch-curator
  cron:
    name:    "{{ elasticsearch_curator_cron_job_item.description|default('Curate Elasticsearch Indices') }}"
    minute:  "{{ elasticsearch_curator_cron_job_item.minute|default('*') }}"
    hour:    "{{ elasticsearch_curator_cron_job_item.hour|default('*') }}"
    day:     "{{ elasticsearch_curator_cron_job_item.day|default('*') }}"
    weekday: "{{ elasticsearch_curator_cron_job_item.weekday|default('*') }}"
    month:   "{{ elasticsearch_curator_cron_job_item.month|default('*') }}"
    user:    "{{ elasticsearch_curator_cron_job_item.user|default('root') }}"
    job:     "{{ elasticsearch_curator_cron_job_item.command|default(elasticsearch_curator_cron_job_command) }}"
    cron_file: elasticsearch-curator
  with_items: "{{ elasticsearch_curator_cron_jobs }}"
  loop_control:
    loop_var: elasticsearch_curator_cron_job_item
